version: "3.3"
services:
  postgres:
    container_name: "pg_container"
    image: postgres:15.0
    ports:
      - target: 5432
        published: 5432
    volumes:
      - ./pgdata:/postgresql/data
    environment:
      PGDATA: /postgresql/data
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root