version: "3.9"
services:
  postgres:
    container_name: "pg_container"
    image: postgres:15.0
    ports:
      - target: 5432
        published: 5432
    volumes:
      - ./pgdata:/postgresql/data
    environment:
      PGDATA: /postgresql/data
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
  pg-admin:
    image: dpage/pgadmin4
    ports:
      - target: 80
        published: 5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin